# Common configuration for Perfume Genie 2.0 (ESP8266 and ESP32)
# This file contains all shared configuration that works on both platforms
# Designed to be imported as a remote package from GitHub
# Repository: github.com/pvizeli/esphome-genie

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: false
  comment: "${comment}"
  min_version: 2024.6.0
  project:
    name: "pvizeli.genie"
    version: "${project_version}"
  on_boot:
    - priority: 600
      then:
        - light.turn_on:
            id: status_led
            transition_length: 0s
            red: 100%
            green: 100%
            blue: 100%

# Enable logging
logger:
  level: INFO  # Reduce logging to save space (DEBUG uses more memory)

# Enable Home Assistant API
api:
  encryption:   # Uses key set by Home Assistant

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_http_request

# Enable HTTP requests for OTA updates (SSL disabled to save memory)
http_request:
  verify_ssl: false

# Update component to check for new firmware from GitHub releases
update:
  - platform: http_request
    name: Firmware
    id: update_http_request
    source: https://pvizeli.github.io/esphome-genie/firmware/esphome-genie.manifest.json

wifi:
  on_connect:
    - light.turn_on:
        id: status_led
        brightness: 100%
        red: 0%
        green: 0%
        blue: 100%
  on_disconnect:
    - light.turn_on:
        id: status_led
        brightness: 100%
        red: 100%
        green: 0%
        blue: 0%

# Get time from ha
time:
  - platform: homeassistant
    id: homeassistant_time

number:
  - platform: template
    name: "Fan Auto-Off Delay"
    id: fan_auto_off_delay
    optimistic: true
    restore_value: true
    min_value: 1
    max_value: 180
    initial_value: 30
    step: 10
    unit_of_measurement: min

binary_sensor:
# WIFI Status
  - platform: status
    name: "Wifi Status"
    icon: "mdi:wifi"

# Fan, button, and script configuration is platform-specific
# See genie-2.yml for ESP8266 (speed platform with GPIO4 PWM)
# See genie-3.yml for ESP32-C6 (hbridge platform with GPIO18/GPIO19)
# Status LED configuration is also platform-specific
# See genie-2.yml for ESP8266 (WS2812 addressable LED via neopixelbus)
# See genie-3.yml for ESP32-C6 (Common-anode RGB LED via LEDC PWM)
