# Common configuration for Perfume Genie (ESP8266 and ESP32)
# This file contains all shared configuration that works on both platforms
# Designed to be imported as a remote package from GitHub
# Repository: github.com/pvizeli/esphome-genie

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: false
  comment: "${comment}"
  min_version: 2024.6.0
  project:
    name: "pvizeli.genie"
    version: "${project_version}"
  on_boot:
    - priority: 600
      then:
        - light.turn_on:
            id: status_led
            transition_length: 0s
            red: 100%
            green: 100%
            blue: 100%

# Enable logging
logger:
  level: INFO  # Reduce logging to save space (DEBUG uses more memory)

# Enable Home Assistant API
api:
  encryption:   # Uses key set by Home Assistant

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_http_request

# Enable HTTP requests for OTA updates (SSL disabled to save memory)
http_request:
  verify_ssl: false

# Update component to check for new firmware from GitHub releases
update:
  - platform: http_request
    name: Firmware
    id: update_http_request
    source: https://pvizeli.github.io/esphome-genie/firmware/esphome-genie.manifest.json

wifi:
  on_connect:
    - light.turn_on:
        id: status_led
        brightness: 100%
        red: 0%
        green: 0%
        blue: 100%
  on_disconnect:
    - light.turn_on:
        id: status_led
        brightness: 100%
        red: 100%
        green: 0%
        blue: 0%

# Get time from Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time

number:
  - platform: template
    name: "Fan Auto-Off Delay"
    id: fan_auto_off_delay
    entity_category: config
    optimistic: true
    restore_value: true
    min_value: 0
    max_value: 180
    initial_value: 30
    step: 10
    unit_of_measurement: min

# Auto-off script (defined before fan so it can be referenced)
script:
  - id: auto_off_fan
    mode: restart
    then:
      - if:
          condition:
            lambda: 'return id(fan_auto_off_delay).state > 0;'
          then:
            - delay: !lambda "return (int(id(fan_auto_off_delay).state) * 60) * 1000;"
            - fan.turn_off: fan_toggle

binary_sensor:
# WIFI Status
  - platform: status
    name: "Wifi Status"
    icon: "mdi:wifi"

# Rear button fan toggle
  - platform: gpio
    name: Genie button
    id: genie_button
    icon: "mdi:gesture-tap-button"
    internal: true
    pin:
      number: ${button_pin}
      inverted: true
      mode:
        input: true
        pullup: true
    on_click:
      then:
        - fan.toggle: fan_toggle

# Fan control with LED status feedback
fan:
  - platform: speed
    id: fan_toggle
    output: fan_speed
    name: "Perfume Genie Fan"
    speed_count: 4
    on_turn_off:
      - light.turn_on:
          id: status_led
          brightness: 100%
          red: 0%
          green: 0%
          blue: 100%
    on_turn_on:
      - light.turn_on:
          id: status_led
          brightness: 100%
          red: 0%
          green: 100%
          blue: 0%
      - script.execute: auto_off_fan

# Platform-specific output and LED configuration
# See genie-2.yml for ESP8266 (esp8266_pwm output on GPIO4, WS2812 LED)
# See genie-3.yml for ESP32-C6 (ledc output on GPIO18, RGB LED)
