# Perfume Genie 2.0 - ESP8266 Version

# Dashboard Import Configuration
dashboard_import:
  package_import_url: github://pvizeli/esphome-genie/genie-2.yml@main
  import_full_config: false

substitutions:
  name: perfume-genie2
  friendly_name: Perfume Genie 2 ESP8266
  comment: Perfume Genie 2.0 ESP8266.
  # GPIO pin assignments for ESP8266
  button_pin: GPIO3
  fan_pin: GPIO4
  led_pin: GPIO15

esp8266:
  board: esp_wroom_02

# Platform-specific PWM output for ESP8266
output:
  - platform: esp8266_pwm
    id: fan_speed
    pin: ${fan_pin}
    frequency: "21kHz"
    min_power: 0%
    max_power: 100%

# ESP8266-specific: WiFi fallback AP and Captive Portal
wifi:
  # Enable fallback hotspot (captive portal) in case WiFi connection fails
  ap:
    ssid: "${name} Fallback"
    password: "config123"

# ESP8266-specific: Captive Portal for easy WiFi setup
captive_portal:

# ESP8266-specific: Status LED using NeoPixelBus
light:
  - platform: neopixelbus
    name: status_leds
    id: status_led
    variant: WS2812
    pin: ${led_pin}
    num_leds: 1
    type: GRB
    method: ESP8266_UART1
    internal: true

# Import common configuration from GitHub
packages:
  genie_common: github://pvizeli/esphome-genie/common.yml@main
