# Perfume Genie 3.0 - ESP32 Version

# Dashboard Import Configuration
dashboard_import:
  package_import_url: github://pvizeli/esphome-genie/genie-3.yml
  import_full_config: false

substitutions:
  name: perfume-genie3
  friendly_name: Perfume Genie 3 ESP32-C6
  comment: Perfume Genie 3.0 ESP32-C6.
  project_version: dev  # This will be replaced by GitHub workflows during release builds
  # GPIO pin assignments for ESP32-C6
  button_pin: GPIO17
  fan_pin_a: GPIO18
  fan_pin_b: GPIO19
  led_red_pin: GPIO23
  led_green_pin: GPIO22
  led_blue_pin: GPIO3

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf

# Platform-specific PWM output for ESP32
output:
  - platform: ledc
    id: fan_output_a
    pin: ${fan_pin_a}
    frequency: "25kHz"

  - platform: ledc
    id: fan_output_b
    pin: ${fan_pin_b}
    frequency: "25kHz"

  - platform: ledc
    id: red_output
    pin: ${led_red_pin}
    inverted: true

  - platform: ledc
    id: green_output
    pin: ${led_green_pin}
    inverted: true

  - platform: ledc
    id: blue_output
    pin: ${led_blue_pin}
    inverted: true

# ESP32-specific: Improv via Bluetooth for easy WiFi setup
# Press the physical button to authorize WiFi provisioning
esp32_improv:
  authorizer: genie_button

# ESP32-specific: Enable Bluetooth proxy
bluetooth_proxy:
  active: true

# ESP32-specific: RGB Status LED using LEDC PWM
light:
  - platform: rgb
    name: status_leds
    id: status_led
    red: red_output
    green: green_output
    blue: blue_output
    internal: true

# Import common configuration from GitHub
packages:
  genie_common: github://pvizeli/esphome-genie/common.yml

# ESP32-C6 specific: H-bridge fan control
fan:
  - platform: hbridge
    id: fan_toggle
    name: "Perfume Genie Fan"
    pin_a: fan_output_a
    pin_b: fan_output_b
    speed_count: 4
    on_turn_off:
      - light.turn_on:
          id: status_led
          brightness: 100%
          red: 0%
          green: 0%
          blue: 100%
    on_turn_on:
      - light.turn_on:
          id: status_led
          brightness: 100%
          red: 0%
          green: 100%
          blue: 0%
      - script.execute: auto_off_fan
