# Perfume Genie 3.0 - ESP32 Version

# Dashboard Import Configuration
dashboard_import:
  package_import_url: github://pvizeli/esphome-genie/genie-3.yml@main
  import_full_config: false

substitutions:
  name: perfume-genie3
  friendly_name: Perfume Genie 3
  comment: Perfume Genie 3.0 ESP32-C6.
  project_version: dev  # This will be replaced by GitHub workflows during release builds
  # GPIO pin assignments for ESP32-C6
  button_pin: GPIO3
  fan_pin: GPIO4
  led_pin: GPIO15

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf
    sdkconfig_options:
      # Optimize for smaller firmware size
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
      # Reduce Bluetooth connections to save space
      CONFIG_BT_NIMBLE_MAX_CONNECTIONS: "3"

# Platform-specific PWM output for ESP32
output:
  - platform: ledc
    id: fan_speed
    pin: ${fan_pin}
    frequency: "21kHz"
    min_power: 0%
    max_power: 100%

# ESP32-specific: Improv via Bluetooth for easy WiFi setup
# Press the physical button to authorize WiFi provisioning
esp32_improv:
  authorizer: genie_button

# ESP32-specific: Enable Bluetooth proxy
bluetooth_proxy:
  active: true

# Enable HTTP requests for OTA updates from GitHub releases (ESP32 uses SSL)
http_request:

# Update component to check for new firmware from GitHub releases
update:
  - platform: http_request
    name: Firmware
    id: update_http_request
    source: https://pvizeli.github.io/esphome-genie/firmware/esphome-genie.manifest.json

# ESP32-specific: Status LED using RMT LED Strip (for ESP-IDF)
light:
  - platform: esp32_rmt_led_strip
    name: status_leds
    id: status_led
    pin: ${led_pin}
    num_leds: 1
    rgb_order: GRB
    chipset: ws2812
    internal: true

# Import common configuration from GitHub
packages:
  genie_common: github://pvizeli/esphome-genie/common.yml@main
