# Perfume Genie 3.0 - ESP32 Version

# Dashboard Import Configuration
dashboard_import:
  package_import_url: github://pvizeli/esphome-genie/genie-3.yml@main
  import_full_config: false

substitutions:
  name: perfume-genie3
  friendly_name: Perfume Genie 3
  comment: Perfume Genie 3.0 ESP32-C6.
  # GPIO pin assignments for ESP32-C6
  button_pin: GPIO3
  fan_pin: GPIO4
  led_pin: GPIO15
  # NeoPixelBus method for ESP-IDF (ESP32-C6)
  led_method: ESP32_RMT_1

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf

# Platform-specific PWM output for ESP32
output:
  - platform: ledc
    id: fan_speed
    pin: ${fan_pin}
    frequency: "21kHz"
    min_power: 0%
    max_power: 100%

# ESP32-specific: Improv via Bluetooth for easy WiFi setup
esp32_improv:
  authorizer: none

# ESP32-specific: Enable Bluetooth proxy
bluetooth_proxy:
  active: true

# Import common configuration from GitHub
packages:
  genie_common: github://pvizeli/esphome-genie/common.yml@main
